// Canvas registration metadata for the shadcn components (labels, props, icons).

// ─── CANVAS REGISTRATION METADATA ───────────────────────────────────────────

const colorOptions = [
  { label: "Default", name: "default" },
  { label: "Primary", name: "primary" },
  { label: "Secondary", name: "secondary" },
  { label: "Destructive", name: "destructive" },
  { label: "Ghost", name: "ghost" },
  { label: "Link", name: "link" },
];

const sizeOptions = [
  { label: "Default", name: "default" },
  { label: "Small", name: "sm" },
  { label: "Large", name: "lg" },
  { label: "Icon", name: "icon" },
];


type MetaLike = import("@webstudio-is/sdk").WsComponentMeta & { category: string; icon: string };

export const shadcnMetas: Record<string, unknown> = {
  ShadcnButton: {
    type: "container",
    label: "Button",
    category: "shadcn",
    icon: "🔘",
    description: "shadcn/ui action button.",
    props: {
      variant: { type: "enum", control: "select", label: "Variant", defaultValue: "default", options: colorOptions },
      size: { type: "enum", control: "select", label: "Size", defaultValue: "default", options: sizeOptions },
      isDisabled: { type: "boolean", label: "Disabled", defaultValue: false },
    },
  },
  ShadcnInput: {
    type: "container",
    label: "Input",
    category: "shadcn",
    icon: "📝",
    props: {
      placeholder: { type: "string", label: "Placeholder", defaultValue: "Search..." },
      type: { type: "string", label: "Type", defaultValue: "text" },
      isDisabled: { type: "boolean", label: "Disabled", defaultValue: false },
    },
  },
  ShadcnTextarea: {
    type: "container",
    label: "Textarea",
    category: "shadcn",
    icon: "📑",
    props: {
      placeholder: { type: "string", label: "Placeholder", defaultValue: "Type message..." },
      isDisabled: { type: "boolean", label: "Disabled", defaultValue: false },
    },
  },
  ShadcnCheckbox: {
    type: "container",
    label: "Checkbox",
    category: "shadcn",
    icon: "☑️",
    props: {
      isChecked: { type: "boolean", label: "Checked", defaultValue: true },
      isDisabled: { type: "boolean", label: "Disabled", defaultValue: false },
    },
  },
  ShadcnSwitch: {
    type: "container",
    label: "Switch",
    category: "shadcn",
    icon: "🔀",
    props: {
      isChecked: { type: "boolean", label: "Checked", defaultValue: true },
      isDisabled: { type: "boolean", label: "Disabled", defaultValue: false },
    },
  },
  ShadcnRadioGroup: {
    type: "container",
    label: "RadioGroup",
    category: "shadcn",
    icon: "🔘",
    props: {
      label: { type: "string", label: "Label", defaultValue: "Select option" },
      defaultValue: { type: "string", label: "Default Value", defaultValue: "a" },
    },
  },
  ShadcnSelect: {
    type: "container",
    label: "Select",
    category: "shadcn",
    icon: "🔽",
    props: {
      placeholder: { type: "string", label: "Placeholder", defaultValue: "Select option" },
      defaultValue: { type: "string", label: "Value", defaultValue: "Active" },
    },
  },
  ShadcnCombobox: {
    type: "container",
    label: "Combobox",
    category: "shadcn",
    icon: "🔍",
    props: {
      placeholder: { type: "string", label: "Placeholder", defaultValue: "Select item..." },
    },
  },
  ShadcnCalendar: {
    type: "container",
    label: "Calendar",
    category: "shadcn",
    icon: "📅",
    props: {},
  },
  ShadcnDatePicker: {
    type: "container",
    label: "DatePicker",
    category: "shadcn",
    icon: "📆",
    props: {
      placeholder: { type: "string", label: "Placeholder", defaultValue: "Pick a date" },
    },
  },
  ShadcnInputOTP: {
    type: "container",
    label: "InputOTP",
    category: "shadcn",
    icon: "🔢",
    props: {},
  },
  ShadcnLabel: {
    type: "container",
    label: "Label",
    category: "shadcn",
    icon: "🏷️",
    props: {},
  },
  ShadcnSlider: {
    type: "container",
    label: "Slider",
    category: "shadcn",
    icon: "🎚️",
    props: {
      defaultValue: { type: "number", label: "Value (%)", defaultValue: 50 },
    },
  },
  ShadcnToggle: {
    type: "container",
    label: "Toggle",
    category: "shadcn",
    icon: "⭐",
    props: {
      isPressed: { type: "boolean", label: "Pressed", defaultValue: false },
    },
  },
  ShadcnToggleGroup: {
    type: "container",
    label: "ToggleGroup",
    category: "shadcn",
    icon: "🗂️",
    props: {},
  },
  ShadcnTabs: {
    type: "container",
    label: "Tabs",
    category: "shadcn",
    icon: "📑",
    props: {},
  },
  ShadcnBreadcrumb: {
    type: "container",
    label: "Breadcrumb",
    category: "shadcn",
    icon: "🥖",
    props: {},
  },
  ShadcnPagination: {
    type: "container",
    label: "Pagination",
    category: "shadcn",
    icon: "🔢",
    props: {},
  },
  ShadcnNavigationMenu: {
    type: "container",
    label: "NavigationMenu",
    category: "shadcn",
    icon: "🗺️",
    props: {},
  },
  ShadcnMenubar: {
    type: "container",
    label: "Menubar",
    category: "shadcn",
    icon: "💻",
    props: {},
  },
  ShadcnContextMenu: {
    type: "container",
    label: "ContextMenu",
    category: "shadcn",
    icon: "🖱️",
    props: {},
  },
  ShadcnDropdownMenu: {
    type: "container",
    label: "DropdownMenu",
    category: "shadcn",
    icon: "⬇️",
    props: {},
  },
  ShadcnSidebar: {
    type: "container",
    label: "Sidebar",
    category: "shadcn",
    icon: "🗄️",
    props: {},
  },
  ShadcnCommand: {
    type: "container",
    label: "Command",
    category: "shadcn",
    icon: "⌨️",
    props: {},
  },
  ShadcnDialog: {
    type: "container",
    label: "Dialog",
    category: "shadcn",
    icon: "💬",
    props: {},
  },
  ShadcnAlertDialog: {
    type: "container",
    label: "AlertDialog",
    category: "shadcn",
    icon: "⚠️",
    props: {},
  },
  ShadcnPopover: {
    type: "container",
    label: "Popover",
    category: "shadcn",
    icon: "🎈",
    props: {},
  },
  ShadcnTooltip: {
    type: "container",
    label: "Tooltip",
    category: "shadcn",
    icon: "ℹ️",
    props: {},
  },
  ShadcnHoverCard: {
    type: "container",
    label: "HoverCard",
    category: "shadcn",
    icon: "📇",
    props: {},
  },
  ShadcnDrawer: {
    type: "container",
    label: "Drawer",
    category: "shadcn",
    icon: "🗃️",
    props: {},
  },
  ShadcnSheet: {
    type: "container",
    label: "Sheet",
    category: "shadcn",
    icon: "📄",
    props: {},
  },
  ShadcnSonner: {
    type: "container",
    label: "Sonner",
    category: "shadcn",
    icon: "🔔",
    props: {},
  },
  ShadcnToast: {
    type: "container",
    label: "Toast",
    category: "shadcn",
    icon: "🍞",
    props: {},
  },
  ShadcnCard: {
    type: "container",
    label: "Card",
    category: "shadcn",
    icon: "🎴",
    props: {},
  },
  ShadcnSeparator: {
    type: "rich-text-child",
    label: "Separator",
    category: "shadcn",
    icon: "➖",
    props: {
      orientation: { type: "enum", control: "select", label: "Orientation", defaultValue: "horizontal", options: [{ label: "Horizontal", name: "horizontal" }, { label: "Vertical", name: "vertical" }] },
    },
  },
  ShadcnResizable: {
    type: "container",
    label: "Resizable",
    category: "shadcn",
    icon: "↕️",
    props: {},
  },
  ShadcnScrollArea: {
    type: "container",
    label: "ScrollArea",
    category: "shadcn",
    icon: "📜",
    props: {},
  },
  ShadcnAspectRatio: {
    type: "container",
    label: "AspectRatio",
    category: "shadcn",
    icon: "🖼️",
    props: {},
  },
  ShadcnCollapsible: {
    type: "container",
    label: "Collapsible",
    category: "shadcn",
    icon: "🗂️",
    props: {
      label: { type: "string", label: "Label", defaultValue: "Settings panel" },
    },
  },
  ShadcnAccordion: {
    type: "container",
    label: "Accordion",
    category: "shadcn",
    icon: "🪗",
    props: {},
  },
  ShadcnCarousel: {
    type: "container",
    label: "Carousel",
    category: "shadcn",
    icon: "🎠",
    props: {},
  },
  ShadcnRow: {
    type: "container",
    label: "Row (Grid)",
    category: "Layout",
    icon: "⊞",
    props: {
      gap: { type: "string", label: "Gap", defaultValue: "16px" },
    },
  },
  ShadcnCol: {
    type: "container",
    label: "Column",
    category: "Layout",
    icon: "▯",
    props: {
      span: { type: "number", label: "Column Span (1-12)", defaultValue: 6 },
    },
  },
  ShadcnContainer: {
    type: "container",
    label: "Container",
    category: "Layout",
    icon: "📦",
    props: {
      direction: { type: "enum", control: "select", label: "Direction", defaultValue: "column", options: [{ label: "Row", name: "row" }, { label: "Column", name: "column" }] },
      justify: { type: "enum", control: "select", label: "Justify", defaultValue: "start", options: [{ label: "Start", name: "start" }, { label: "Center", name: "center" }, { label: "End", name: "end" }, { label: "Between", name: "between" }, { label: "Around", name: "around" }, { label: "Evenly", name: "evenly" }] },
      align: { type: "enum", control: "select", label: "Align", defaultValue: "stretch", options: [{ label: "Start", name: "start" }, { label: "Center", name: "center" }, { label: "End", name: "end" }, { label: "Stretch", name: "stretch" }, { label: "Baseline", name: "baseline" }] },
      gap: { type: "string", label: "Gap", defaultValue: "0px" },
      padding: { type: "string", label: "Padding", defaultValue: "16px" },
      wrap: { type: "enum", control: "select", label: "Wrap", defaultValue: "nowrap", options: [{ label: "No Wrap", name: "nowrap" }, { label: "Wrap", name: "wrap" }, { label: "Wrap Reverse", name: "wrap-reverse" }] },
    },
  },
  ShadcnSection: {
    type: "container",
    label: "Section",
    category: "Layout",
    icon: "📐",
    props: {
      padding: { type: "string", label: "Padding", defaultValue: "48px 24px" },
      maxWidth: { type: "string", label: "Max Width", defaultValue: "1200px" },
      background: { type: "string", label: "Background", defaultValue: "transparent" },
    },
  },
  ShadcnFlexRow: {
    type: "container",
    label: "Flex Row",
    category: "Layout",
    icon: "↔️",
    props: {
      gap: { type: "string", label: "Gap", defaultValue: "12px" },
      justify: { type: "enum", control: "select", label: "Justify", defaultValue: "start", options: [{ label: "Start", name: "start" }, { label: "Center", name: "center" }, { label: "End", name: "end" }, { label: "Between", name: "between" }, { label: "Around", name: "around" }] },
      align: { type: "enum", control: "select", label: "Align", defaultValue: "center", options: [{ label: "Start", name: "start" }, { label: "Center", name: "center" }, { label: "End", name: "end" }, { label: "Stretch", name: "stretch" }] },
      wrap: { type: "enum", control: "select", label: "Wrap", defaultValue: "wrap", options: [{ label: "No Wrap", name: "nowrap" }, { label: "Wrap", name: "wrap" }] },
    },
  },
  ShadcnSpacer: {
    type: "rich-text-child",
    label: "Spacer",
    category: "Layout",
    icon: "↕️",
    props: {
      height: { type: "string", label: "Height", defaultValue: "24px" },
    },
  },
  ShadcnAvatar: {
    type: "container",
    label: "Avatar",
    category: "Display",
    icon: "👤",
    props: {
      src: { type: "string", label: "Avatar URL", defaultValue: "" },
      name: { type: "string", label: "User Name", defaultValue: "John Doe" },
    },
  },
  ShadcnBadge: {
    type: "container",
    label: "Badge",
    category: "Display",
    icon: "🏷️",
    props: {
      variant: { type: "enum", control: "select", label: "Variant", defaultValue: "default", options: [{ label: "Default", name: "default" }, { label: "Secondary", name: "secondary" }, { label: "Destructive", name: "destructive" }, { label: "Outline", name: "outline" }] },
    },
  },
  ShadcnTable: {
    type: "container",
    label: "Table",
    category: "Display",
    icon: "📊",
    props: {},
  },
  ShadcnSkeleton: {
    type: "container",
    label: "Skeleton",
    category: "Display",
    icon: "💀",
    props: {},
  },
  ShadcnProgress: {
    type: "container",
    label: "Progress",
    category: "Display",
    icon: "📈",
    props: {
      value: { type: "number", label: "Value (%)", defaultValue: 60 },
    },
  },
  ShadcnCode: {
    type: "container",
    label: "Code",
    category: "Typography",
    icon: "💻",
    props: {},
  },
  ShadcnKbd: {
    type: "container",
    label: "Kbd",
    category: "Typography",
    icon: "⌨️",
    props: {},
  },
  ShadcnText: {
    type: "rich-text-child",
    label: "Text",
    category: "Typography",
    icon: "📄",
    props: {
      fontSize: { type: "string", label: "Font Size", defaultValue: "16px" },
      fontWeight: { type: "string", label: "Font Weight", defaultValue: "400" },
      color: { type: "string", label: "Color", defaultValue: "inherit" },
      textAlign: { type: "enum", control: "select", label: "Text Align", defaultValue: "left", options: [{ label: "Left", name: "left" }, { label: "Center", name: "center" }, { label: "Right", name: "right" }, { label: "Justify", name: "justify" }] },
    },
  },
  ShadcnHeading: {
    type: "rich-text-child",
    label: "Heading",
    category: "Typography",
    icon: "🔤",
    props: {
      level: { type: "number", label: "Level (1-6)", defaultValue: 2 },
      textAlign: { type: "enum", control: "select", label: "Text Align", defaultValue: "left", options: [{ label: "Left", name: "left" }, { label: "Center", name: "center" }, { label: "Right", name: "right" }] },
      color: { type: "string", label: "Color", defaultValue: "inherit" },
    },
  },
  ShadcnLink: {
    type: "rich-text-child",
    label: "Link",
    category: "Typography",
    icon: "🔗",
    props: {
      href: { type: "string", label: "URL", defaultValue: "#" },
      target: { type: "enum", control: "select", label: "Target", defaultValue: "_self", options: [{ label: "Same Tab", name: "_self" }, { label: "New Tab", name: "_blank" }] },
      color: { type: "string", label: "Color", defaultValue: "var(--ui-accent)" },
    },
  },
  ShadcnDataTable: {
    type: "container",
    label: "DataTable",
    category: "Advanced",
    icon: "🗃️",
    props: {},
  },
  ShadcnChart: {
    type: "container",
    label: "Chart",
    category: "Advanced",
    icon: "📈",
    props: {},
  },
};
